// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// auc_2
double auc_2(NumericMatrix x);
RcppExport SEXP _AccTestKgrps_auc_2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(auc_2(x));
    return rcpp_result_gen;
END_RCPP
}
// auc_1
double auc_1(NumericVector x, NumericVector y);
RcppExport SEXP _AccTestKgrps_auc_1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(auc_1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// auc_3
double auc_3(NumericMatrix x);
RcppExport SEXP _AccTestKgrps_auc_3(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(auc_3(x));
    return rcpp_result_gen;
END_RCPP
}
// f_hist_C
NumericVector f_hist_C(NumericVector X, NumericVector x_eval, double h);
RcppExport SEXP _AccTestKgrps_f_hist_C(SEXP XSEXP, SEXP x_evalSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(f_hist_C(X, x_eval, h));
    return rcpp_result_gen;
END_RCPP
}
// tauc_C
double tauc_C(NumericVector tt1, NumericVector tt2, NumericVector tt3, NumericVector tt4);
RcppExport SEXP _AccTestKgrps_tauc_C(SEXP tt1SEXP, SEXP tt2SEXP, SEXP tt3SEXP, SEXP tt4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tt1(tt1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt2(tt2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt3(tt3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt4(tt4SEXP);
    rcpp_result_gen = Rcpp::wrap(tauc_C(tt1, tt2, tt3, tt4));
    return rcpp_result_gen;
END_RCPP
}
// trapz_C
double trapz_C(NumericVector fx, double hx);
RcppExport SEXP _AccTestKgrps_trapz_C(SEXP fxSEXP, SEXP hxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fx(fxSEXP);
    Rcpp::traits::input_parameter< double >::type hx(hxSEXP);
    rcpp_result_gen = Rcpp::wrap(trapz_C(fx, hx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AccTestKgrps_auc_2", (DL_FUNC) &_AccTestKgrps_auc_2, 1},
    {"_AccTestKgrps_auc_1", (DL_FUNC) &_AccTestKgrps_auc_1, 2},
    {"_AccTestKgrps_auc_3", (DL_FUNC) &_AccTestKgrps_auc_3, 1},
    {"_AccTestKgrps_f_hist_C", (DL_FUNC) &_AccTestKgrps_f_hist_C, 3},
    {"_AccTestKgrps_tauc_C", (DL_FUNC) &_AccTestKgrps_tauc_C, 4},
    {"_AccTestKgrps_trapz_C", (DL_FUNC) &_AccTestKgrps_trapz_C, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_AccTestKgrps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
