# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auc_2 <- function(x) {
    .Call(`_AccTestKgrps_auc_2`, x)
}

auc_1 <- function(x, y) {
    .Call(`_AccTestKgrps_auc_1`, x, y)
}

auc_3 <- function(x) {
    .Call(`_AccTestKgrps_auc_3`, x)
}

f_hist_C <- function(X, x_eval, h) {
    .Call(`_AccTestKgrps_f_hist_C`, X, x_eval, h)
}

tauc_C <- function(tt1, tt2, tt3, tt4) {
    .Call(`_AccTestKgrps_tauc_C`, tt1, tt2, tt3, tt4)
}

trapz_C <- function(fx, hx) {
    .Call(`_AccTestKgrps_trapz_C`, fx, hx)
}

